#!/bin/bash

#data_path=/ASD/CIVET_Data_checkBeforeRemove/CONTE_1-2year_MULTISEGandCIVET_Data_Sept2017/CONTE/neo*/CIVET/neo*/surfaces/*
left_data_path=/work/mansisak/data/Conte/sa_ct_norm/left_surf_sa_ct_norm/*
right_data_path=/work/mansisak/data/Conte/sa_ct_norm/right_surf_sa_ct_norm/*
fly_by_path=../fly-by-cnn/src/py


left_surface=""
left_out=""
left_sd=""

right_surface=""
right_out=""
right_sd=""

for f in $left_data_path
    do
        
        left_surface=$f
        left_out="/work/mansisak/data/Conte/sa_ct_sd_norm/sa_ct_sd_depth_norm_vtk_conte/left_$(echo $f | egrep -o 'neo[^r]*' | head -n1 )r.vtk"
        left_sd="/work/mansisak/data/Conte/sa_ct_sd_norm/sulcal_depth_text_files/left_$(echo $f | egrep -o 'neo[^r]*' | head -n1 )r_sulcal_depth_left.txt"
        echo $left_surface
        echo $left_out
        echo $left_sd
        #Do left processing:
        echo "LEFT PROCESSING"
        python3 $fly_by_path/add_property_to_surface.py --surf $left_surface --property_file $left_sd  --property_name "SULCAL_DEPTH" --out $left_out 
    done
for f in $right_data_path
    do
        
        right_surface=$f
        right_out="/work/mansisak/data/Conte/sa_ct_sd_norm/sa_ct_sd_depth_norm_vtk_conte/right_$(echo $f | egrep -o 'neo[^r]*' | head -n1 )r.vtk"
        right_sd="/work/mansisak/data/Conte/sa_ct_sd_norm/sulcal_depth_text_files/right_$(echo $f | egrep -o 'neo[^r]*' | head -n1 )r_sulcal_depth_right.txt"
        echo $right_surface
        echo $right_out
        echo $right_sd
        #Do right processing:
        echo "right PROCESSING"
        python3 $fly_by_path/add_property_to_surface.py --surf $right_surface --property_file $right_sd  --property_name "SULCAL_DEPTH" --out $right_out 
    done
