#!/bin/bash

#data_path_left=/work/mansisak/data/Conte/sa_ct_sd_norm/left_surf_sa_ct_sd_depth_norm_seq/*
#data_path_right=/work/mansisak/data/Conte/sa_ct_sd_norm/right_surf_sa_ct_sd_depth_norm_seq/*

#csv_file_train_yr=/work/mansisak/data/Conte/sa_ct_sd_norm/sa_ct_sd_depth_norm_DL_sets/train.csv 
#csv_file_test_yr=/work/mansisak/data/Conte/sa_ct_sd_norm/sa_ct_sd_depth_norm_DL_sets/test.csv 
#csv_file_val_yr=/work/mansisak/data/Conte/sa_ct_sd_norm/sa_ct_sd_depth_norm_DL_sets/val.csv 

data_path_left=/work/mansisak/data/Conte/sa_ct_sd_norm/left_surf_sa_ct_depth_norm_seq/*
data_path_right=/work/mansisak/data/Conte/sa_ct_sd_norm/right_surf_sa_ct_depth_norm_seq/*

csv_file_train_yr=/work/mansisak/data/Conte/sa_ct_sd_norm/sa_ct_depth_norm_DL_sets/train.csv 
csv_file_test_yr=/work/mansisak/data/Conte/sa_ct_sd_norm/sa_ct_depth_norm_DL_sets/test.csv 
csv_file_val_yr=/work/mansisak/data/Conte/sa_ct_sd_norm/sa_ct_depth_norm_DL_sets/val.csv 

input=input
cases=cases

for l in $data_path_left
    do
    left=${l:76}
    #left=${l:79}
    echo $left
    echo $left>>$input
    done

for r in $data_path_right
    do
    right=${r:78}
    #right=${r:81}
    echo $right
    echo $right>>$input
    done

sort $input | uniq -d >> $cases

rm test.txt train.txt val.txt

shuf cases | split -a1 -d -l $(( $(wc -l <cases) * 80 / 100 )) - output
mv output1 test.txt
shuf output0 | split -a1 -d -l $(( $(wc -l <output0) * 88 / 100 )) - train
mv train0 train.txt
mv train1 val.txt
rm output0
rm input
rm cases


rm $csv_file_train_yr $csv_file_test_yr $csv_file_val_yr

echo "File_path,Label">>$csv_file_train_yr
echo "File_path,Label">>$csv_file_test_yr
echo "File_path,Label">>$csv_file_val_yr


for f in $data_path_left
    do
        #left=${f:79}
        left=${f:76}
        echo $left
        #get label
        if [[ "$f" == *"1year.nrrd" ]]
            then
                label=1
        else
            label=2
        fi
        #train
        if grep -Fxq "$left" train.txt
            then
                #echo $left
                echo $f,$label>>$csv_file_train_yr
        fi
        #test
        if grep -Fxq "$left" test.txt
            then
                #echo $left
                echo $f,$label>>$csv_file_test_yr
        fi
        #val
        if grep -Fxq "$left" val.txt
            then
                #echo $left
                echo $f,$label>>$csv_file_val_yr
        fi
    done

for f in $data_path_right
    do
        #right=${f:81}
        right=${f:78}
        echo $right
        #get label
        if [[ "$f" == *"1year.nrrd" ]]
            then
                label=1
        else
            label=2
        fi
        #train
        if grep -Fxq "$right" train.txt
            then
                echo $f,$label>>$csv_file_train_yr
        fi
        #test
        if grep -Fxq "$right" test.txt
            then
                echo $f,$label>>$csv_file_test_yr
        fi
        #val
        if grep -Fxq "$right" val.txt
            then
                echo $f,$label>>$csv_file_val_yr
        fi
    done
