#!/bin/bash

data_path_left=/work/mansisak/data/Conte/sa_ct_sd_norm/left_surf_sa_ct_sd_depth_norm_seq_inf/*
data_path_right=/work/mansisak/data/Conte/sa_ct_sd_norm/right_surf_sa_ct_sd_depth_norm_seq_inf/*

csv_file_train_yr=/work/mansisak/data/Conte/sa_ct_sd_norm/train_yr_inf.csv 
csv_file_test_yr=/work/mansisak/data/Conte/sa_ct_sd_norm/test_yr_inf.csv 
csv_file_val_yr=/work/mansisak/data/Conte/sa_ct_sd_norm/val_yr_inf.csv 

input=input
cases=cases

#want 3 separate CSV files: 70% for train, 20% for test, 10% for validation
#left and right hemispheres of the same subject cannot be split amoung the 3 different sections
#430 cases in total(430 left, 430 right) (with matching hemispheres)
#302 for train, 86 for test, 42 for validation


for l in $data_path_left
    do
    left=${l:83}
    #echo $left
    echo $left>>$input
    done

for r in $data_path_right
    do
    right=${r:85}
    #echo $right
    echo $right>>$input
    done

sort $input | uniq -d >> $cases

rm test.txt train.txt val.txt

shuf cases | split -a1 -d -l $(( $(wc -l <cases) * 80 / 100 )) - output
mv output1 test.txt
shuf output0 | split -a1 -d -l $(( $(wc -l <output0) * 88 / 100 )) - train
mv train0 train.txt
mv train1 val.txt
rm output0
rm input
rm cases


rm $csv_file_train_yr $csv_file_test_yr $csv_file_val_yr

echo "File_path,Label">>$csv_file_train_yr
echo "File_path,Label">>$csv_file_test_yr
echo "File_path,Label">>$csv_file_val_yr


for f in $data_path_left
    do
        left=${f:83}
        echo $left
        #get label
        if [[ "$f" == *"1year.nrrd" ]]
            then
                label=1
        else
            label=2
        fi
        #train
        if grep -Fxq "$left" train.txt
            then
                #echo $left
                echo $f,$label>>$csv_file_train_yr
        fi
        #test
        if grep -Fxq "$left" test.txt
            then
                #echo $left
                echo $f,$label>>$csv_file_test_yr
        fi
        #val
        if grep -Fxq "$left" val.txt
            then
                #echo $left
                echo $f,$label>>$csv_file_val_yr
        fi
    done

for f in $data_path_right
    do
        right=${f:85}
        echo $right
        #get label
        if [[ "$f" == *"1year.nrrd" ]]
            then
                label=1
        else
            label=2
        fi
        #train
        if grep -Fxq "$right" train.txt
            then
                echo $f,$label>>$csv_file_train_yr
        fi
        #test
        if grep -Fxq "$right" test.txt
            then
                echo $f,$label>>$csv_file_test_yr
        fi
        #val
        if grep -Fxq "$right" val.txt
            then
                echo $f,$label>>$csv_file_val_yr
        fi
    done
