#!/bin/bash

data_path_left=/work/mansisak/data/Conte/sa_ct_norm/left_surf_sa_ct_norm_seq/*
data_path_right=/work/mansisak/data/Conte/sa_ct_norm/right_surf_sa_ct_norm_seq/*
csv_file_left=/work/mansisak/data/Conte/sa_ct_norm/left_feature_set.csv 
csv_file_right=/work/mansisak/data/Conte/sa_ct_norm/right_feature_set.csv 

echo "File_path,Label">>$csv_file_left

for f in $data_path_left
    do
        if [[ "$f" == *"1year.nrrd" ]]
            then
                label=1
        else
            label=2
        fi
        echo $f,$label>>$csv_file_left
    done

echo "File_path,Label">>$csv_file_right

for f in $data_path_right
    do
        if [[ "$f" == *"1year.nrrd" ]]
            then
                label=1
        else
            label=2
        fi
        echo $f,$label>>$csv_file_right
    done
