#!/bin/bash

data_path=/ASD/mansi_flyby/sa_ct_sd_vtk_conte_wm_surf/*
fly_by_path=../fly-by-cnn/src/py
out=""
out_path=/ASD/mansi_flyby/large_set_surf_sa_ct_sd_depth_norm_seq

for f in $data_path
    do
        if [[ $f == *"left"* ]]
            then
                out="$(echo $f | egrep -o 'left_neo[^r]*' | head -n1 )r.nrrd"
                echo "left surf:"
                echo $out
                finished_out="$(echo $out | egrep -o 'left_neo[^r]*' | head -n1 )r_rot9.nrrd"
                if test -f "$out_path/$finished_out";then
                    echo "$finished_out exists"
                    echo "move onto next case"
                    continue
                fi
                python3 $fly_by_path/fly_by_features.py --surf $f --spiral 16 --out $out_path/$out --norm_shader 0 --scale_factor 0.8049401485964498 --resolution 256 --radius 2 --split_z 1 --use_z 1 --point_features SURFACE_AREA CORTICAL_THICKNESS SULCAL_DEPTH --point_features_concat 1 --random_rotation 1 --n_rotations 10
                echo "done"

                #python3 $fly_by_path/fly_by_features.py --surf $f --spiral 16 --out ../data/Conte/sa_ct_sd_norm/left_surf_sa_ct_depth_norm_seq/$out --norm_shader 0 --scale_factor 0.8049401485964498 --resolution 256 --radius 2 --split_z 1 --use_z 1 --point_features SURFACE_AREA CORTICAL_THICKNESS --point_features_concat 1
                #python3 $fly_by_path/fly_by_features.py --surf $f --spiral 16 --out ../data/Conte/sa_ct_sd_norm/left_surf_depth_norm_seq/$out --norm_shader 0 --scale_factor 0.8049401485964498 --resolution 256 --radius 2 --split_z 1 --use_z 1 --point_features_concat 1
        fi

        if [[ $f == *"right"* ]]
            then
                out="$(echo $f | egrep -o 'right_neo[^r]*' | head -n1 )r.nrrd"
                echo "right surf:"
                echo $out
                finished_out="$(echo $out | egrep -o 'right_neo[^r]*' | head -n1 )r_rot9.nrrd"
                if test -f "$out_path/$finished_out";then
                    echo "$finished_out exists"
                    echo "move onto next case"
                    continue
                fi
                python3 $fly_by_path/fly_by_features.py --surf $f --spiral 16 --out $out_path/$out --norm_shader 0 --scale_factor 0.7971917611384308 --resolution 256 --radius 2 --split_z 1 --use_z 1 --point_features SURFACE_AREA CORTICAL_THICKNESS SULCAL_DEPTH --point_features_concat 1  --random_rotation 1 --n_rotations 10 
                echo "done"

                #python3 $fly_by_path/fly_by_features.py --surf $f --spiral 16 --out ../data/Conte/sa_ct_sd_norm/right_surf_sa_ct_depth_norm_seq/$out --norm_shader 0 --scale_factor 0.7971917611384308 --resolution 256 --radius 2 --split_z 1 --use_z 1 --point_features SURFACE_AREA CORTICAL_THICKNESS --point_features_concat 1
                #python3 $fly_by_path/fly_by_features.py --surf $f --spiral 16 --out ../data/Conte/sa_ct_sd_norm/right_surf_depth_norm_seq/$out --norm_shader 0 --scale_factor 0.7971917611384308 --resolution 256 --radius 2 --split_z 1 --use_z 1 --point_features_concat 1
        fi

    done
