#!/bin/bash

data_path=/work/mansisak/data/Conte/right_surf_sa_ct_norm/*
fly_by_path=../fly-by-cnn/src/py
property=""
surface=""
out=""

for f in $data_path
    do
        out="$(echo $f | egrep -o 'right_neo[^r]*' | head -n1 )r.nrrd"
        echo $out
        python3 $fly_by_path/fly_by_features.py --surf $f --spiral 16 --out ../data/Conte/right_surf_sa_ct_norm_seq/$out --norm_shader 0 --scale_factor 0.7971917611384308 --resolution 256 --radius 2 --split_z 1 --point_features normals SURFACE_AREA CORTICAL_THICKNESS

    done
